#!/usr/bin/env python3
"""Converts art/source/*.png into firmware image data for Mershy.

Outputs (both committed, so a firmware build doesn't need Python/Pillow):
  src/assets/mershy.bin  -- all pixel data, embedded into flash
  src/mershy_assets.h    -- table of parts: name, offset, position, size

The base is master.png scaled to the 466x466 panel as plain RGB565. Every
other PNG is a variant of the master with one feature changed; the script
cuts that feature's region (by filename prefix, see REGIONS) and stores it
as RGB565A8 with feathered edges, so it blends seamlessly over the base.

Run after adding or changing art:
    art/.venv/bin/python art/build_assets.py
(one-time setup: python3 -m venv art/.venv && art/.venv/bin/pip install pillow numpy)
"""
import glob
import os
import sys

import numpy as np
from PIL import Image

SIZE = 466
FEATHER = 5  # px of soft edge on each part

# Screen-space rectangles (x0, y0, x1, y1) per feature, measured by diffing
# the variants against master.png and padding by a few px. They depend on
# the master's framing: if master.png is replaced, re-measure them.
REGIONS = {
    "brows": (136, 84, 332, 148),
    "eyes": (146, 140, 320, 190),
    "mouth": (136, 186, 370, 390),
}

# Drawing order on screen is brows -> eyes -> mouth (bottom to top), set in
# buddy_ui.cpp. Eyes sit above brows because the brow region's lower edge
# overlaps the upper eyelid; the other way round, open-eye lashes from a brow
# variant show through a closed-eye blink.

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(HERE, "source")
PROJECT = os.path.dirname(HERE)
BIN_PATH = os.path.join(PROJECT, "src", "assets", "mershy.bin")
HEADER_PATH = os.path.join(PROJECT, "src", "mershy_assets.h")


def load(path):
    img = Image.open(path).convert("RGB")
    if img.size != (SIZE, SIZE):
        img = img.resize((SIZE, SIZE), Image.LANCZOS)
    return np.asarray(img).astype(np.float32)


def to_rgb565(rgb):
    """float RGB array -> little-endian RGB565 bytes (LVGL's native layout)."""
    rgb = np.clip(rgb + 0.5, 0, 255).astype(np.uint16)
    r, g, b = rgb[..., 0] >> 3, rgb[..., 1] >> 2, rgb[..., 2] >> 3
    return ((r << 11) | (g << 5) | b).astype("<u2").tobytes()


def prepare_base(rgb):
    """Pure black outside the round panel and in near-black areas, so those
    AMOLED pixels are fully off instead of faintly glowing."""
    yy, xx = np.mgrid[0:SIZE, 0:SIZE]
    r = SIZE / 2.0
    outside = (xx + 0.5 - r) ** 2 + (yy + 0.5 - r) ** 2 > r * r
    near_black = rgb.max(axis=2) < 10
    out = rgb.copy()
    out[outside | near_black] = 0
    return out


def feather_mask(w, h):
    """255 inside, smooth ramp to 0 over FEATHER px at every edge."""
    def ramp(n):
        t = np.minimum(np.arange(n) + 0.5, n - np.arange(n) - 0.5) / FEATHER
        t = np.clip(t, 0, 1)
        return t * t * (3 - 2 * t)  # smoothstep
    return (np.outer(ramp(h), ramp(w)) * 255 + 0.5).astype(np.uint8)


def main():
    master_path = os.path.join(SRC_DIR, "master.png")
    if not os.path.isfile(master_path):
        sys.exit("art/source/master.png is missing")
    master = load(master_path)

    blob = bytearray()
    entries = []

    def add(name, data, x, y, w, h, has_alpha):
        while len(blob) % 4:  # keep every image 4-byte aligned for LVGL
            blob.append(0)
        entries.append((name, len(blob), x, y, w, h, has_alpha))
        blob.extend(data)

    base = prepare_base(master)
    add("base", to_rgb565(base), 0, 0, SIZE, SIZE, 0)

    variants = sorted(
        p for p in glob.glob(os.path.join(SRC_DIR, "*.png"))
        if os.path.basename(p) != "master.png"
    )
    for path in variants:
        name = os.path.splitext(os.path.basename(path))[0]
        feature = name.split("_", 1)[0]
        if feature not in REGIONS:
            print(f"skip {name}: unknown feature prefix '{feature}'")
            continue
        x0, y0, x1, y1 = REGIONS[feature]
        w, h = x1 - x0, y1 - y0
        img = load(path)

        drift = np.abs(img - master)
        # Border pixels should match the master closely; a big difference
        # means the generator moved something and the seams will show.
        border = np.concatenate([
            drift[y0, x0:x1].ravel(), drift[y1 - 1, x0:x1].ravel(),
            drift[y0:y1, x0].ravel(), drift[y0:y1, x1 - 1].ravel(),
        ]).mean()
        crop = prepare_base(img)[y0:y1, x0:x1]
        add(name, to_rgb565(crop) + feather_mask(w, h).tobytes(), x0, y0, w, h, 1)
        warn = "  <-- high edge drift, seams may show" if border > 25 else ""
        print(f"{name:20s} {feature:6s} {w}x{h} at ({x0},{y0})  edge drift {border:4.1f}{warn}")

    os.makedirs(os.path.dirname(BIN_PATH), exist_ok=True)
    with open(BIN_PATH, "wb") as f:
        f.write(blob)

    lines = [
        "// Generated by art/build_assets.py -- do not edit.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint32_t offset;       // into mershy.bin",
        "    uint16_t x, y, w, h;   // screen position and size",
        "    uint8_t has_alpha;     // 1 = RGB565A8, 0 = RGB565",
        "} mershy_part_t;",
        "",
        f"#define MERSHY_PART_COUNT {len(entries)}",
        "",
        "static const mershy_part_t kMershyParts[MERSHY_PART_COUNT] = {",
    ]
    for name, off, x, y, w, h, a in entries:
        lines.append(f'    {{"{name}", {off}u, {x}, {y}, {w}, {h}, {a}}},')
    lines += ["};", ""]
    with open(HEADER_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"\n{len(entries)} images, {len(blob) / 1024:.0f} KB -> {os.path.relpath(BIN_PATH, PROJECT)}")


if __name__ == "__main__":
    main()
