# PlatformIO pre-build script: writes src/api_keys.h (gitignored) from
# ANTHROPIC_API_KEY / DEEPGRAM_API_KEY / ELEVENLABS_API_KEY.
#
# Looks in the process environment first, then in a gitignored .env at the
# project root -- builds started from the VS Code PlatformIO button often
# don't load ~/.zshrc, so .env is the fallback.
import os
import sys

Import("env")  # noqa: F821 -- injected by PlatformIO

KEYS = ["ANTHROPIC_API_KEY", "DEEPGRAM_API_KEY", "ELEVENLABS_API_KEY"]

project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
out_path = os.path.join(project_dir, "src", "api_keys.h")


def read_dotenv(path):
    values = {}
    if not os.path.isfile(path):
        return values
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            name, value = line.split("=", 1)
            name = name.replace("export ", "").strip()
            values[name] = value.strip().strip('"').strip("'")
    return values


dotenv = read_dotenv(os.path.join(project_dir, ".env"))
resolved = {}
missing = []
for key in KEYS:
    value = os.environ.get(key) or dotenv.get(key)
    if value:
        resolved[key] = value
    else:
        missing.append(key)

if missing:
    sys.stderr.write(
        "\n*** gen_api_keys.py: missing %s\n"
        "*** Export them in your shell (~/.zshrc) or add them to %s/.env\n\n"
        % (", ".join(missing), project_dir)
    )
    env.Exit(1)  # noqa: F821

contents = "// Generated by scripts/gen_api_keys.py -- do not edit, do not commit.\n"
contents += "#pragma once\n\n"
for key in KEYS:
    escaped = resolved[key].replace("\\", "\\\\").replace('"', '\\"')
    contents += '#define %s "%s"\n' % (key, escaped)

# Only rewrite on change so the header doesn't trigger a rebuild every time.
existing = None
if os.path.isfile(out_path):
    with open(out_path) as f:
        existing = f.read()
if existing != contents:
    with open(out_path, "w") as f:
        f.write(contents)
    print("gen_api_keys.py: wrote src/api_keys.h")
