// Generated by art/build_assets.py -- do not edit.
#pragma once

#include <stdint.h>

typedef struct {
    const char *name;
    uint32_t offset;       // into mershy.bin
    uint16_t x, y, w, h;   // screen position and size
    uint8_t has_alpha;     // 1 = RGB565A8, 0 = RGB565
} mershy_part_t;

#define MERSHY_PART_COUNT 5

static const mershy_part_t kMershyParts[MERSHY_PART_COUNT] = {
    {"base", 0u, 0, 0, 466, 466, 0},
    {"brows_one_up", 434312u, 136, 84, 196, 64, 1},
    {"eyes_closed", 471944u, 146, 140, 174, 50, 1},
    {"mouth_grin", 498044u, 136, 186, 234, 204, 1},
    {"mouth_talk_small", 641252u, 136, 186, 234, 204, 1},
};
